### ISSUE TITLE
For unknown functions

### ISSUE THREAD

**Issue by OpenSELab** [rahulgopinath/rahulgopinath.github.io#17]
https://github.com/rahulgopinath/rahulgopinath.github.io/blame/99ff21de22608eea25606d40e7291063976cc9a6/notebooks/2019-12-08-python-controlflow.py#L55

When I tried to run the code locally, the compiler told me that the function `__canvas__` was not defined.
I've already installed the required dependencies.

So I hope the author can provide some guidance, thanks!

**Comment by vrthra** [comment]
Hi, thank you for your bug report. If you change
```
if __name__ == '__main__':
    graphics = WebGraphics()
```
to
```
if __name__ == '__main__':
    graphics = CLIGraphics()
```
does it help?

**Comment by OpenSELab** [comment]
> Hi, thank you for your bug report. If you change
> 
> ```
> if __name__ == '__main__':
>     graphics = WebGraphics()
> ```
> 
> to
> 
> ```
> if __name__ == '__main__':
>     graphics = CLIGraphics()
> ```
> 
> does it help?

Thanks! That's all right now.

**Comment by vrthra** [comment]
Added a comment in https://github.com/rahulgopinath/rahulgopinath.github.io/commit/8b9fdd9dc148b4a6f368fcf5253dbc654ef797e8
